# pull official base image
FROM node:18-alpine3.14 as builder

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY . /app

RUN npm run build

FROM nginx:1.23.2-alpine

COPY --from=builder /app/build /usr/share/nginx/html/jumbf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]